### ISSUE TITLE
Server shut-down after start up

### ISSUE THREAD

**Issue by jrmhaig** [connected-web/product-monitor#36]
``` sh
/Users/haigj01/workspace/github/jrmhaig/tv-wall-pong/node_modules/product-monitor/lib/api/npmStatus.js:126
        error: error,
               ^
ReferenceError: error is not defined
    at dealWithResult (/Users/haigj01/workspace/github/jrmhaig/tv-wall-pong/node_modules/product-monitor/lib/api/npmStatus.js:126:16)
    at /Users/haigj01/workspace/github/jrmhaig/tv-wall-pong/node_modules/product-monitor/lib/monitor/commandRunner.js:30:5
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Socket.<anonymous> (child_process.js:956:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

**Comment by johnbeech** [comment]
Thanks... hopefully fixed that issue now. The error was untrapped while reporting the actual error - which I assume was caused because the installed version of npm was < 2.0.0, it was 1.3.6 from what I remember seeing when I was sat with you earlier.

In summary:

``` js
    if (result.error || result.stderr) {
      response = {
        data: false,
        message: 'Exec error: ' + command + ', ' + result.error + ', ' + result.stderr,
        error: error,
        cacheDuration: instance.cacheDuration,
        command: command,
        updatesRequired: false,
        versions: versions
      };
    } else {
      response = interpretOutput(command, result.stdout);
    }
```

Should have been:

``` js
    if (result.error || result.stderr) {
      response = {
        data: false,
        message: 'Exec error: ' + command + ', ' + result.error + ', ' + result.stderr,
        error: result.error,
        cacheDuration: instance.cacheDuration,
        command: command,
        updatesRequired: false,
        versions: versions
      };
    } else {
      response = interpretOutput(command, result.stdout);
    }
```
